{% set version = '2.4.7' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dlnm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dlnm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dlnm/dlnm_{{ version }}.tar.gz
  sha256: e426dabc1d82355cb1249a9b5c9172cedbddb4ab64059bb96976976491e07c55

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mgcv
    - r-nlme
    - r-tsmodel
  run:
    - r-base
    - r-mgcv
    - r-nlme
    - r-tsmodel

test:
  commands:
    - $R -e "library('dlnm')"           # [not win]
    - "\"%R%\" -e \"library('dlnm')\""  # [win]

about:
  home: https://github.com/gasparrini/dlnm, http://www.ag-myresearch.com/package-dlnm
  license: GPL-2.0-or-later
  summary: Collection of functions for distributed lag linear and non-linear models.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: dlnm
# Type: Package
# Version: 2.4.7
# Date: 2021-10-07
# Title: Distributed Lag Non-Linear Models
# Description: Collection of functions for distributed lag linear and non-linear models.
# Author: Antonio Gasparrini [aut, cre], Ben Armstrong [aut], Fabian Scheipl [ctb]
# Maintainer: Antonio Gasparrini <antonio.gasparrini@lshtm.ac.uk>
# Authors@R: c( person("Antonio","Gasparrini",role=c("aut","cre"),email="antonio.gasparrini@lshtm.ac.uk"), person("Ben","Armstrong",role="aut",email="ben.armstrong@lshtm.ac.uk"), person("Fabian","Scheipl",role="ctb",email="fabian.scheipl@stat.uni-muenchen.de"))
# Imports: stats, graphics, grDevices, utils, splines, nlme, mgcv, tsModel
# Depends: R (>= 3.2)
# Suggests: survival, lme4, gee, geepack, mixmeta
# URL: https://github.com/gasparrini/dlnm, http://www.ag-myresearch.com/package-dlnm
# License: GPL (>= 2)
# LazyData: yes
# NeedsCompilation: no
# Packaged: 2021-10-07 10:17:29 UTC; anton
# Repository: CRAN
# Date/Publication: 2021-10-07 10:40:05 UTC
